version: "3.7"

services:
  marketplace:
    # DOCKER_BUILDKIT=1 docker build . -f marketplace/Dockerfile \
    #                   -t marketplace --secret id=ca.key,src=ca.key  
    image: marketplace
    environment:
      RECOMMENDATIONS_HOST: recommendations
    ports:
      - 5000:5000
    
  recommendations:
    # DOCKER_BUILDKIT=1 docker build . -f recommendations/Dockerfile \
    #                   -t marketplace --secret id=ca.key,src=ca.key    
    image: recommendations
