version: "3.7"

services:
  marketplace:
    build:
      context: .
      dockerfile: marketplace/Dockerfile
    environment:
      RECOMMENDATIONS_HOST: recommendations
    ports:
      - 5000:5000
    
  recommendations:
    build:
      context: .
      dockerfile: recommendations/Dockerfile
